package logbook.internal;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import logbook.dto.ShipInfoDto;

/**
 * 艦娘
 *
 */
public class Ship {

    /**
     * 艦娘プリセッTo値
     */
    private static final Map<String, ShipInfoDto> SHIP = new ConcurrentHashMap<String, ShipInfoDto>() {
        {
            this.put("1", new ShipInfoDto("Mutsuki", "DD", "Mutsuki", 20, 15, 15));
            this.put("2", new ShipInfoDto("Kisaragi", "DD", "Kisaragi", 20, 15, 15));
            this.put("3", new ShipInfoDto("Naka Christmas", "CL", "Naka", 20, 25, 25));
            this.put("4", ShipInfoDto.EMPTY);
            this.put("5", ShipInfoDto.EMPTY);
            this.put("6", new ShipInfoDto("Nagatsuki", "DD", "Nagatsuki", 20, 15, 15));
            this.put("7", new ShipInfoDto("Mikazuki", "DD", "Mikazuki", 20, 15, 15));
            this.put("8", ShipInfoDto.EMPTY);
            this.put("9", new ShipInfoDto("Fubuki", "DD", "Fubuki", 20, 20, 15));
            this.put("10", new ShipInfoDto("Shirayuki", "DD", "Shirayuki", 20, 20, 15));
            this.put("11", new ShipInfoDto("Miyuki", "DD", "Miyuki", 20, 20, 15));
            this.put("12", new ShipInfoDto("Isonami", "DD", "Isonami", 20, 20, 15));
            this.put("13", new ShipInfoDto("Ayanami", "DD", "Ayanami", 20, 20, 15));
            this.put("14", new ShipInfoDto("Shikinami", "DD", "Shikinami", 20, 20, 15));
            this.put("15", new ShipInfoDto("Akebono", "DD", "Akebono", 20, 20, 15));
            this.put("16", new ShipInfoDto("Ushio", "DD", "Ushio", 20, 20, 15));
            this.put("17", new ShipInfoDto("Kagerou", "DD", "Kagerou", 20, 20, 15));
            this.put("18", new ShipInfoDto("Shiranui", "DD", "Shiranui", 20, 20, 15));
            this.put("19", new ShipInfoDto("Kuroshio", "DD", "Kuroshio", 20, 20, 15));
            this.put("20", new ShipInfoDto("Yukikaze", "DD", "Yukikaze", 20, 20, 15));
            this.put("21", new ShipInfoDto("Nagara", "CL", "Nagara", 20, 25, 25));
            this.put("22", new ShipInfoDto("Isuzu", "CL", "Isuzu", 12, 25, 25));
            this.put("23", new ShipInfoDto("Yura", "CL", "Yura", 20, 25, 25));
            this.put("24", new ShipInfoDto("Ooi", "CL", "Ooi", 10, 25, 25));
            this.put("25", new ShipInfoDto("Kitakami", "CL", "Kitakami", 10, 25, 25));
            this.put("26", new ShipInfoDto("Fusou", "BB", "Fusou", 20, 120, 85));
            this.put("27", new ShipInfoDto("Yamashiro", "BB", "Yamashiro", 20, 120, 85));
            this.put("28", new ShipInfoDto("Satsuki", "DD", "Satsuki", 20, 15, 15));
            this.put("29", new ShipInfoDto("Fumizuki", "DD", "Fumizuki", 20, 15, 15));
            this.put("30", new ShipInfoDto("Kikuzuki", "DD", "Kikuzuki", 20, 15, 15));
            this.put("31", new ShipInfoDto("Mochizuki", "DD", "Mochizuki", 20, 15, 15));
            this.put("32", new ShipInfoDto("Hatsuyuki", "DD", "Hatsuyuki", 20, 20, 15));
            this.put("33", new ShipInfoDto("Murakumo", "DD", "Murakumo", 20, 20, 15));
            this.put("34", new ShipInfoDto("Akatsuki", "DD", "Akatsuki", 20, 20, 15));
            this.put("35", new ShipInfoDto("Hibiki", "DD", "Hibiki", 20, 20, 15));
            this.put("36", new ShipInfoDto("Ikazuchi", "DD", "Ikazuchi", 20, 20, 15));
            this.put("37", new ShipInfoDto("Inazuma", "DD", "Inazuma", 20, 20, 15));
            this.put("38", new ShipInfoDto("Hatsuharu", "DD", "Hatsuharu", 20, 20, 15));
            this.put("39", new ShipInfoDto("Nenohi", "DD", "Nenohi", 20, 20, 15));
            this.put("40", new ShipInfoDto("Wakaba", "DD", "Wakaba", 20, 20, 15));
            this.put("41", new ShipInfoDto("Hatsushimo", "DD", "Hatsushimo", 20, 20, 15));
            this.put("42", new ShipInfoDto("Shiratsuyu", "DD", "Shiratsuyu", 20, 20, 15));
            this.put("43", new ShipInfoDto("Shigure", "DD", "Shigure", 20, 20, 15));
            this.put("44", new ShipInfoDto("Murasame", "DD", "Murasame", 20, 20, 15));
            this.put("45", new ShipInfoDto("Yuudachi", "DD", "Yuudachi", 20, 20, 15));
            this.put("46", new ShipInfoDto("Samidare", "DD", "Samidare", 20, 20, 15));
            this.put("47", new ShipInfoDto("Suzukaze", "DD", "Suzukaze", 20, 20, 15));
            this.put("48", new ShipInfoDto("Arare", "DD", "Arare", 20, 20, 15));
            this.put("49", new ShipInfoDto("Kasumi", "DD", "Kasumi", 20, 20, 15));
            this.put("50", new ShipInfoDto("Shimakaze", "DD", "Shimakaze", 20, 25, 20));
            this.put("51", new ShipInfoDto("Tenryuu", "CL", "Tenryuu", 20, 20, 25));
            this.put("52", new ShipInfoDto("Tatsuta", "CL", "Tatsuta", 20, 20, 25));
            this.put("53", new ShipInfoDto("Natori", "CL", "Natori", 20, 25, 25));
            this.put("54", new ShipInfoDto("Sendai", "CL", "Sendai", 20, 25, 25));
            this.put("55", new ShipInfoDto("Jintsuu", "CL", "Jintsuu", 20, 25, 25));
            this.put("56", new ShipInfoDto("Naka", "CL", "Naka", 20, 25, 25));
            this.put("57", new ShipInfoDto("Ooi Kai", "CLT", "Ooi Kai", 50, 50, 25));
            this.put("58", new ShipInfoDto("Kitakami Kai", "CLT", "Kitakami Kai", 50, 50, 25));
            this.put("59", new ShipInfoDto("Furutaka", "CA", "Furutaka", 25, 50, 35));
            this.put("60", new ShipInfoDto("Kako", "CA", "Kako", 25, 50, 35));
            this.put("61", new ShipInfoDto("Aoba", "CA", "Aoba", 25, 50, 35));
            this.put("62", new ShipInfoDto("Myoukou", "CA", "Myoukou", 25, 65, 40));
            this.put("63", new ShipInfoDto("Nachi", "CA", "Nachi", 25, 65, 40));
            this.put("64", new ShipInfoDto("Ashigara", "CA", "Ashigara", 25, 65, 40));
            this.put("65", new ShipInfoDto("Haguro", "CA", "Haguro", 25, 65, 40));
            this.put("66", new ShipInfoDto("Takao", "CA", "Takao", 25, 65, 40));
            this.put("67", new ShipInfoDto("Atago", "CA", "Atago", 25, 65, 40));
            this.put("68", new ShipInfoDto("Maya", "CA", "Maya", 18, 65, 40));
            this.put("69", new ShipInfoDto("Choukai", "CA", "Choukai", 25, 65, 40));
            this.put("70", new ShipInfoDto("Mogami", "CA", "Mogami", 10, 65, 40));
            this.put("71", new ShipInfoDto("Tone", "CA", "Tone", 25, 60, 45));
            this.put("72", new ShipInfoDto("Chikuma", "CA", "Chikuma", 25, 60, 45));
            this.put("73", new ShipInfoDto("Mogami Kai", "CAV", "Mogami", 0, 55, 50));
            this.put("74", new ShipInfoDto("Shouhou", "CVL", "Shouhou", 25, 35, 35));
            this.put("75", new ShipInfoDto("Hiyou", "CVL", "Hiyou", 25, 40, 40));
            this.put("76", new ShipInfoDto("Ryuujou", "CVL", "Ryuujou", 25, 35, 35));
            this.put("77", new ShipInfoDto("Ise", "BB", "Ise", 10, 120, 85));
            this.put("78", new ShipInfoDto("Kongou", "BB", "Kongou", 25, 110, 80));
            this.put("79", new ShipInfoDto("Haruna", "BB", "Haruna", 25, 110, 80));
            this.put("80", new ShipInfoDto("Nagato", "BB", "Nagato", 30, 130, 100));
            this.put("81", new ShipInfoDto("Mutsu", "BB", "Mutsu", 30, 130, 100));
            this.put("82", new ShipInfoDto("Ise Kai", "BBV", "Ise", 0, 105, 95));
            this.put("83", new ShipInfoDto("Akagi", "CV", "Akagi", 30, 55, 60));
            this.put("84", new ShipInfoDto("Kaga", "CV", "Kaga", 30, 55, 60));
            this.put("85", new ShipInfoDto("Kirishima", "BB", "Kirishima", 25, 110, 80));
            this.put("86", new ShipInfoDto("Hiei", "BB", "Hiei", 25, 110, 80));
            this.put("87", new ShipInfoDto("Hyuuga", "BB", "Hyuuga", 10, 120, 85));
            this.put("88", new ShipInfoDto("Hyuuga Kai", "BBV", "Hyuuga", 0, 105, 95));
            this.put("89", new ShipInfoDto("Houshou", "CVL", "Houshou", 25, 25, 25));
            this.put("90", new ShipInfoDto("Souryuu", "CV", "Souryuu", 30, 50, 50));
            this.put("91", new ShipInfoDto("Hiryuu", "CV", "Hiryuu", 30, 50, 50));
            this.put("92", new ShipInfoDto("Junyou", "CVL", "Junyou", 25, 40, 40));
            this.put("93", new ShipInfoDto("Oboro", "DD", "Oboro", 20, 20, 15));
            this.put("94", new ShipInfoDto("Sazanami", "DD", "Sazanami", 20, 20, 15));
            this.put("95", new ShipInfoDto("Asashio", "DD", "Asashio", 20, 20, 15));
            this.put("96", new ShipInfoDto("Ooshio", "DD", "Ooshio", 20, 20, 15));
            this.put("97", new ShipInfoDto("Michishio", "DD", "Michishio", 20, 20, 15));
            this.put("98", new ShipInfoDto("Arashio", "DD", "Arashio", 20, 20, 15));
            this.put("99", new ShipInfoDto("Kuma", "CL", "Kuma", 20, 25, 25));
            this.put("100", new ShipInfoDto("Tama", "CL", "Tama", 20, 25, 25));
            this.put("101", new ShipInfoDto("Kiso", "CL", "Kiso", 20, 25, 25));
            this.put("102", new ShipInfoDto("Chitose", "AV", "Chitose", 10, 35, 35));
            this.put("103", new ShipInfoDto("Chiyoda", "AV", "Chiyoda", 10, 35, 35));
            this.put("104", new ShipInfoDto("Chitose Kai", "AV", "Chitose", 12, 40, 35));
            this.put("105", new ShipInfoDto("Chiyoda Kai", "AV", "Chiyoda", 12, 40, 35));
            this.put("106", new ShipInfoDto("Chitose A", "AV", "Chitose", 15, 45, 35));
            this.put("107", new ShipInfoDto("Chiyoda A", "AV", "Chiyoda", 15, 45, 35));
            this.put("108", new ShipInfoDto("Chitose CVL", "CVL", "Chitose", 35, 40, 40));
            this.put("109", new ShipInfoDto("Chiyoda CVL", "CVL", "Chiyoda", 35, 40, 40));
            this.put("110", new ShipInfoDto("Shoukaku", "CV", "Shoukaku", 30, 55, 55));
            this.put("111", new ShipInfoDto("Zuikaku", "CV", "Zuikaku", 25, 55, 55));
            this.put("112", new ShipInfoDto("Zuikaku Kai", "CV", "Zuikaku", 0, 70, 65));
            this.put("113", new ShipInfoDto("Kinu", "CL", "Kinu", 17, 25, 25));
            this.put("114", new ShipInfoDto("Abukuma", "CL", "Abukuma", 17, 25, 25));
            this.put("115", new ShipInfoDto("Yuubari", "CL", "Yuubari", 25, 30, 20));
            this.put("116", new ShipInfoDto("Zuihou", "CVL", "Zuihou", 25, 35, 35));
            this.put("117", new ShipInfoDto("Zuihou Kai", "CVL", "Zuihou", 0, 40, 40));
            this.put("118", new ShipInfoDto("Ooi Kai 2", "CLT", "Ooi", 0, 75, 25));
            this.put("119", new ShipInfoDto("Kitakami Kai 2", "CLT", "Kitakami", 0, 75, 25));
            this.put("120", new ShipInfoDto("Mikuma", "CA", "Mikuma", 30, 65, 40));
            this.put("121", new ShipInfoDto("Mikuma Kai", "CAV", "Mikuma", 0, 55, 50));
            this.put("122", new ShipInfoDto("Maikaze", "DD", "Maikaze", 20, 20, 15));
            this.put("123", new ShipInfoDto("Kinugasa", "CA", "Kinugasa", 25, 50, 35));
            this.put("124", new ShipInfoDto("Suzuya", "CA", "Suzuya", 35, 65, 40));
            this.put("125", new ShipInfoDto("Kumano", "CA", "Kumano", 35, 65, 40));
            this.put("126", new ShipInfoDto("I-168", "SS", "I-168", 50, 20, 10));
            this.put("127", new ShipInfoDto("I-58", "SS", "I-58", 50, 20, 10));
            this.put("128", new ShipInfoDto("I-8", "SS", "I-8", 50, 20, 10));
            this.put("129", new ShipInfoDto("Suzuya Kai", "CAV", "Suzuya", 0, 55, 50));
            this.put("130", new ShipInfoDto("Kumano Kai", "CAV", "Kumano", 0, 55, 50));
            this.put("131", new ShipInfoDto("Yamato", "BB", "Yamato", 60, 300, 250));
            this.put("132", new ShipInfoDto("Akigumo", "DD", "Akigumo", 30, 20, 15));
            this.put("133", new ShipInfoDto("Yuugumo", "DD", "Yuugumo", 30, 20, 15));
            this.put("134", new ShipInfoDto("Makigumo", "DD", "Makigumo", 30, 20, 15));
            this.put("135", new ShipInfoDto("Naganami", "DD", "Naganami", 30, 20, 15));
            this.put("136", new ShipInfoDto("Yamato Kai", "BB", "Yamato", 0, 325, 250));
            this.put("137", new ShipInfoDto("Agano", "CL", "Agano", 35, 355, 30));
            this.put("138", new ShipInfoDto("Noshiro", "CL", "Noshiro", 35, 35, 30));
            this.put("139", new ShipInfoDto("Yahagi", "CL", "Yahagi", 35, 35, 30));
            this.put("140", ShipInfoDto.EMPTY);
            this.put("141", new ShipInfoDto("Isuzu Kai 2", "CL", "Isuzu", 0, 30, 25));
            this.put("142", new ShipInfoDto("Kinugasa Kai 2", "CA", "Kinugasa", 0, 65, 35));
            this.put("143", new ShipInfoDto("Musashi", "BB", "Musashi", 40, 300, 250));
            this.put("144", new ShipInfoDto("Yuudachi Kai 2", "DD", "Yuudachi", 0, 20, 15));
            this.put("145", new ShipInfoDto("Shigure Kai 2", "DD", "Shigure", 0, 20, 15));
            this.put("146", new ShipInfoDto("Kiso Kai 2", "CLT", "Kiso", 0, 50, 25));
            this.put("147", new ShipInfoDto("Верный", "DD", "Hibiki", 0, 25, 15));
            this.put("148", new ShipInfoDto("Musashi Kai", "BB", "Musashi", 0, 325, 250));
            this.put("149", new ShipInfoDto("Kongou Kai 2", "BB", "Kongou", 0, 125, 100));
            this.put("150", new ShipInfoDto("Hiei Kai 2", "BB", "Hiei", 0, 125, 100));
            this.put("151", ShipInfoDto.EMPTY);
            this.put("152", ShipInfoDto.EMPTY);
            this.put("153", new ShipInfoDto("Taihou", "CVB", "Taihou", 40, 65, 70));
            this.put("154", ShipInfoDto.EMPTY);
            this.put("155", new ShipInfoDto("I-401", "SSV", "I-401", 35, 15, 20));
            this.put("156", new ShipInfoDto("Taihou Kai", "CVB", "Taihou", 0, 75, 90));
            this.put("157", ShipInfoDto.EMPTY);
            this.put("158", ShipInfoDto.EMPTY);
            this.put("159", new ShipInfoDto("Jintsuu Kai 2", "CL", "Jintsuu", 0, 35, 25));
            this.put("160", new ShipInfoDto("Naka Kai2", "CL", "Naka", 0, 35, 25));
            this.put("161", new ShipInfoDto("Akitsu Maru", "LHA", "Akitsu Maru", 25, 10, 40));
            this.put("162", ShipInfoDto.EMPTY);
            this.put("163", new ShipInfoDto("Maruyu", "SS", "Maruyu", 20, 5, 10));
            this.put("164", new ShipInfoDto("Yayoi", "DD", "Yayoi", 20, 15, 15));
            this.put("165", new ShipInfoDto("Uzuki", "DD", "Uzuki", 25, 15, 15));
            this.put("166", new ShipInfoDto("Akitsu Maru Kai", "LHA", "Akitsu Maru", 0, 25, 45));
            this.put("167", ShipInfoDto.EMPTY);
            this.put("168", ShipInfoDto.EMPTY);
            this.put("169", ShipInfoDto.EMPTY);
            this.put("170", ShipInfoDto.EMPTY);
            this.put("171", new ShipInfoDto("Bismarck", "BB", "Bismarck", 30, 110, 90));
            this.put("172", new ShipInfoDto("Bismarck Kai", "BB", "Bismarck", 0, 115, 95));
            this.put("173", ShipInfoDto.EMPTY);
            this.put("174", new ShipInfoDto("Z1", "DD", "Z1", 30, 20, 20));
            this.put("175", new ShipInfoDto("Z3", "DD", "Z3", 30, 20, 20));
            this.put("176", ShipInfoDto.EMPTY);
            this.put("177", ShipInfoDto.EMPTY);
            this.put("178", ShipInfoDto.EMPTY);
            this.put("179", ShipInfoDto.EMPTY);
            this.put("180", ShipInfoDto.EMPTY);
            this.put("181", new ShipInfoDto("IONA", "SS", "Arpeggio Iona", 0, 150, 150));
            this.put("182", new ShipInfoDto("TAKAO", "CA", "Arpeggio Takao", 0, 200, 175));
            this.put("183", new ShipInfoDto("HARUNA", "BB", "Arpeggio Haruna", 0, 275, 200));
            this.put("184", ShipInfoDto.EMPTY);
            this.put("185", ShipInfoDto.EMPTY);
            this.put("186", ShipInfoDto.EMPTY);
            this.put("187", ShipInfoDto.EMPTY);
            this.put("188", ShipInfoDto.EMPTY);
            this.put("189", ShipInfoDto.EMPTY);
            this.put("190", new ShipInfoDto("Hatsukaze", "DD", "Hatsukaze", 20, 20, 15));
            this.put("191", new ShipInfoDto("I-19", "SS", "I-19", 50, 20, 10));
            this.put("192", ShipInfoDto.EMPTY);
            this.put("193", ShipInfoDto.EMPTY);
            this.put("194", ShipInfoDto.EMPTY);
            this.put("195", ShipInfoDto.EMPTY);
            this.put("196", ShipInfoDto.EMPTY);
            this.put("197", ShipInfoDto.EMPTY);
            this.put("198", ShipInfoDto.EMPTY);
            this.put("199", ShipInfoDto.EMPTY);
            this.put("200", ShipInfoDto.EMPTY);
            this.put("201", new ShipInfoDto("Fubuki Kai", "DD", "Fubuki", 0, 20, 15));
            this.put("202", new ShipInfoDto("Shirayuki Kai", "DD", "Shirayuki", 0, 20, 15));
            this.put("203", new ShipInfoDto("Hatsuyuki Kai", "DD", "Hatsuyuki", 0, 20, 15));
            this.put("204", new ShipInfoDto("Miyuki Kai", "DD", "Miyuki", 0, 20, 15));
            this.put("205", new ShipInfoDto("Murakumo Kai", "DD", "Murakumo", 0, 20, 15));
            this.put("206", new ShipInfoDto("Isonami Kai", "DD", "Isonami", 0, 20, 15));
            this.put("207", new ShipInfoDto("Ayanami Kai", "DD", "Ayanami", 0, 20, 15));
            this.put("208", new ShipInfoDto("Shikinami Kai", "DD", "Shikinami", 0, 20, 15));
            this.put("209", new ShipInfoDto("Kongou Kai", "BB", "Kongou", 75, 120, 90));
            this.put("210", new ShipInfoDto("Hiei Kai", "BB", "Hiei", 75, 120, 90));
            this.put("211", new ShipInfoDto("Haruna Kai", "BB", "Haruna", 0, 120, 90));
            this.put("212", new ShipInfoDto("Kirishima Kai", "BB", "Kirishima", 0, 120, 90));
            this.put("213", new ShipInfoDto("Tenryuu Kai", "CL", "Tenryuu", 0, 25, 25));
            this.put("214", new ShipInfoDto("Tatsuta Kai", "CL", "Tatsuta", 0, 25, 25));
            this.put("215", new ShipInfoDto("Kuma Kai", "CL", "Kuma", 0, 30, 25));
            this.put("216", new ShipInfoDto("Tama Kai", "CL", "Tama", 0, 30, 25));
            this.put("217", new ShipInfoDto("Kiso Kai", "CL", "Kiso", 65, 30, 25));
            this.put("218", new ShipInfoDto("Nagara Kai", "CL", "Nagara", 0, 30, 25));
            this.put("219", new ShipInfoDto("Isuzu Kai", "CL", "Isuzu", 50, 30, 25));
            this.put("220", new ShipInfoDto("Yura Kai", "CL", "Yura", 0, 30, 25));
            this.put("221", new ShipInfoDto("Natori Kai", "CL", "Natori", 0, 30, 25));
            this.put("222", new ShipInfoDto("Sendai Kai", "CL", "Sendai", 0, 30, 25));
            this.put("223", new ShipInfoDto("Jintsuu Kai", "CL", "Jintsuu", 60, 30, 25));
            this.put("224", new ShipInfoDto("Naka Kai", "CL", "Naka", 48, 30, 25));
            this.put("225", new ShipInfoDto("Kagerou Kai", "DD", "Kagerou", 0, 20, 15));
            this.put("226", new ShipInfoDto("Shiranui Kai", "DD", "Shiranui", 0, 20, 15));
            this.put("227", new ShipInfoDto("Kuroshio Kai", "DD", "Kuroshio", 0, 20, 15));
            this.put("228", new ShipInfoDto("Yukikaze Kai", "DD", "Yukikaze", 0, 20, 15));
            this.put("229", new ShipInfoDto("Shimakaze Kai", "DD", "Shimakaze", 0, 25, 20));
            this.put("230", new ShipInfoDto("Oboro Kai", "DD", "Oboro", 0, 20, 15));
            this.put("231", new ShipInfoDto("Akebono Kai", "DD", "Akebono", 0, 20, 15));
            this.put("232", new ShipInfoDto("Sazanami Kai", "DD", "Sazanami", 0, 20, 15));
            this.put("233", new ShipInfoDto("Ushio Kai", "DD", "Ushio", 0, 20, 15));
            this.put("234", new ShipInfoDto("Akatsuki Kai", "DD", "Akatsuki", 0, 20, 15));
            this.put("235", new ShipInfoDto("Hibiki Kai", "DD", "Hibiki", 70, 20, 15));
            this.put("236", new ShipInfoDto("Ikazuchi Kai", "DD", "Ikazuchi", 0, 20, 15));
            this.put("237", new ShipInfoDto("Inazuma Kai", "DD", "Inazuma", 0, 20, 15));
            this.put("238", new ShipInfoDto("Hatsuharu Kai", "DD", "Hatsuharu", 0, 20, 15));
            this.put("239", new ShipInfoDto("Nenohi Kai", "DD", "Nenohi", 0, 20, 15));
            this.put("240", new ShipInfoDto("Wakaba Kai", "DD", "Wakaba", 0, 20, 15));
            this.put("241", new ShipInfoDto("Hatsushimo Kai", "DD", "Hatsushimo", 0, 20, 15));
            this.put("242", new ShipInfoDto("Shiratsuyu Kai", "DD", "Shiratsuyu", 0, 20, 15));
            this.put("243", new ShipInfoDto("Shigure Kai", "DD", "Shigure", 60, 20, 15));
            this.put("244", new ShipInfoDto("Murasame Kai", "DD", "Murasame", 0, 20, 15));
            this.put("245", new ShipInfoDto("Yuudachi Kai", "DD", "Yuudachi", 55, 20, 15));
            this.put("246", new ShipInfoDto("Samidare Kai", "DD", "Samidare", 0, 20, 15));
            this.put("247", new ShipInfoDto("Suzukaze Kai", "DD", "Suzukaze", 0, 20, 15));
            this.put("248", new ShipInfoDto("Asashio Kai", "DD", "Asashio", 0, 20, 15));
            this.put("249", new ShipInfoDto("Ooshio Kai", "DD", "Ooshio", 0, 20, 15));
            this.put("250", new ShipInfoDto("Michishio Kai", "DD", "Michishio", 0, 20, 15));
            this.put("251", new ShipInfoDto("Arashio Kai", "DD", "Arashio", 0, 20, 15));
            this.put("252", new ShipInfoDto("Arare Kai", "DD", "Arare", 0, 20, 15));
            this.put("253", new ShipInfoDto("Kasumi Kai", "DD", "Kasumi", 0, 20, 15));
            this.put("254", new ShipInfoDto("Mutsuki Kai", "DD", "Mutsuki", 0, 15, 15));
            this.put("255", new ShipInfoDto("Kisaragi Kai", "DD", "Kisaragi", 0, 15, 15));
            this.put("256", new ShipInfoDto("Satsuki Kai", "DD", "Satsuki", 0, 15, 15));
            this.put("257", new ShipInfoDto("Fumizuki Kai", "DD", "Fumizuki", 0, 15, 15));
            this.put("258", new ShipInfoDto("Nagatsuki Kai", "DD", "Nagatsuki", 0, 15, 15));
            this.put("259", new ShipInfoDto("Kikuzuki Kai", "DD", "Kikuzuki", 0, 15, 15));
            this.put("260", new ShipInfoDto("Mikazuki Kai", "DD", "Mikazuki", 0, 15, 15));
            this.put("261", new ShipInfoDto("Mochizuki Kai", "DD", "Mochizuki", 0, 15, 15));
            this.put("262", new ShipInfoDto("Furutaka Kai", "CA", "Furutaka", 0, 55, 35));
            this.put("263", new ShipInfoDto("Kako Kai", "CA", "Kako", 0, 55, 35));
            this.put("264", new ShipInfoDto("Aoba Kai", "CA", "Aoba", 0, 55, 35));
            this.put("265", new ShipInfoDto("Myoukou Kai", "CA", "Myoukou", 0, 70, 40));
            this.put("266", new ShipInfoDto("Nachi Kai", "CA", "Nachi", 0, 70, 40));
            this.put("267", new ShipInfoDto("Ashigara Kai", "CA", "Ashigara", 0, 70, 40));
            this.put("268", new ShipInfoDto("Haguro Kai", "CA", "Haguro", 0, 70, 40));
            this.put("269", new ShipInfoDto("Takao Kai", "CA", "Takao", 0, 70, 40));
            this.put("270", new ShipInfoDto("Atago Kai", "CA", "Atago", 0, 70, 40));
            this.put("271", new ShipInfoDto("Maya Kai", "CA", "Maya", 0, 70, 40));
            this.put("272", new ShipInfoDto("Choukai Kai", "CA", "Choukai", 0, 70, 40));
            this.put("273", new ShipInfoDto("Tone Kai", "CA", "Tone", 0, 65, 45));
            this.put("274", new ShipInfoDto("Chikuma Kai", "CA", "Chikuma", 0, 65, 45));
            this.put("275", new ShipInfoDto("Nagato Kai", "BB", "Nagato", 0, 160, 100));
            this.put("276", new ShipInfoDto("Mutsu Kai", "BB", "Mutsu", 0, 160, 100));
            this.put("277", new ShipInfoDto("Akagi Kai", "CV", "Akagi", 0, 75, 75));
            this.put("278", new ShipInfoDto("Kaga Kai", "CV", "Kaga", 0, 80, 80));
            this.put("279", new ShipInfoDto("Souryuu Kai", "CV", "Souryuu", 0, 65, 65));
            this.put("280", new ShipInfoDto("Hiryuu Kai", "CV", "Hiryuu", 0, 65, 65));
            this.put("281", new ShipInfoDto("Ryuujou Kai", "CVL", "Ryuujou", 0, 40, 40));
            this.put("282", new ShipInfoDto("Shouhou Kai", "CVL", "Shouhou", 0, 40, 40));
            this.put("283", new ShipInfoDto("Hiyou Kai", "CVL", "Hiyou", 0, 45, 45));
            this.put("284", new ShipInfoDto("Junyou Kai", "CVL", "Junyou", 0, 45, 45));
            this.put("285", new ShipInfoDto("Houshou Kai", "CVL", "Houshou", 0, 30, 30));
            this.put("286", new ShipInfoDto("Fusou Kai", "BBV", "Fusou", 0, 105, 95));
            this.put("287", new ShipInfoDto("Yamashiro Kai", "BBV", "Yamashiro", 0, 105, 95));
            this.put("288", new ShipInfoDto("Shoukaku Kai", "CV", "Shoukaku", 0, 70, 65));
            this.put("289", new ShipInfoDto("Kinu Kai", "CL", "Kinu", 0, 35, 25));
            this.put("290", new ShipInfoDto("Abukuma Kai", "CL", "Abukuma", 0, 35, 25));
            this.put("291", new ShipInfoDto("Chitose CVL Kai", "CVL", "Chitose", 50, 40, 45));
            this.put("292", new ShipInfoDto("Chiyoda CVL Kai", "CVL", "Chiyoda", 50, 40, 45));
            this.put("293", new ShipInfoDto("Yuubari Kai", "CL", "Yuubari", 0, 40, 25));
            this.put("294", new ShipInfoDto("Maikaze Kai", "DD", "Maikaze", 0, 20, 15));
            this.put("295", new ShipInfoDto("Kinugasa Kai", "CA", "Kinugasa", 55, 60, 35));
            this.put("296", new ShipInfoDto("Chitose CVL Kai2", "CVL", "Chitose", 0, 40, 45));
            this.put("297", new ShipInfoDto("Chiyoda CVL Kai2", "CVL", "Chiyoda", 0, 40, 45));
            this.put("298", ShipInfoDto.EMPTY);
            this.put("299", ShipInfoDto.EMPTY);
            this.put("300", new ShipInfoDto("Hatsukaze Kai", "DD", "Hatsukaze", 0, 20, 15));
            this.put("301", new ShipInfoDto("Akigumo Kai", "DD", "Akigumo", 0, 20, 15));
            this.put("302", new ShipInfoDto("Yuugumo Kai", "DD", "Yuugumo", 0, 20, 15));
            this.put("303", new ShipInfoDto("Makigumo Kai", "DD", "Makigumo", 0, 20, 15));
            this.put("304", new ShipInfoDto("Naganami Kai", "DD", "Naganami", 0, 20, 15));
            this.put("305", new ShipInfoDto("Agano Kai", "CL", "Agano", 0, 40, 30));
            this.put("306", new ShipInfoDto("Noshiro Kai", "CL", "Noshiro", 0, 40, 30));
            this.put("307", new ShipInfoDto("Yahagi Kai", "CL", "Yahagi", 0, 40, 30));
            this.put("308", new ShipInfoDto("Yayoi Kai", "DD", "Yayoi", 0, 15, 15));
            this.put("309", new ShipInfoDto("Uzuki Kai", "DD", "Uzuki", 0, 15, 15));
            this.put("310", new ShipInfoDto("Z1 Kai", "DD", "Z1", 0, 25, 20));
            this.put("311", new ShipInfoDto("Z3 Kai", "DD", "Z3", 0, 25, 20));
            this.put("312", ShipInfoDto.EMPTY);
            this.put("313", ShipInfoDto.EMPTY);
            this.put("314", ShipInfoDto.EMPTY);
            this.put("315", ShipInfoDto.EMPTY);
            this.put("316", ShipInfoDto.EMPTY);
            this.put("317", ShipInfoDto.EMPTY);
            this.put("318", ShipInfoDto.EMPTY);
            this.put("319", ShipInfoDto.EMPTY);
            this.put("320", ShipInfoDto.EMPTY);
            this.put("321", ShipInfoDto.EMPTY);
            this.put("322", ShipInfoDto.EMPTY);
            this.put("323", ShipInfoDto.EMPTY);
            this.put("324", ShipInfoDto.EMPTY);
            this.put("325", ShipInfoDto.EMPTY);
            this.put("326", ShipInfoDto.EMPTY);
            this.put("327", ShipInfoDto.EMPTY);
            this.put("328", ShipInfoDto.EMPTY);
            this.put("329", ShipInfoDto.EMPTY);
            this.put("330", ShipInfoDto.EMPTY);
            this.put("331", ShipInfoDto.EMPTY);
            this.put("332", ShipInfoDto.EMPTY);
            this.put("333", ShipInfoDto.EMPTY);
            this.put("334", ShipInfoDto.EMPTY);
            this.put("335", ShipInfoDto.EMPTY);
            this.put("336", ShipInfoDto.EMPTY);
            this.put("337", ShipInfoDto.EMPTY);
            this.put("338", ShipInfoDto.EMPTY);
            this.put("339", ShipInfoDto.EMPTY);
            this.put("340", ShipInfoDto.EMPTY);
            this.put("341", ShipInfoDto.EMPTY);
            this.put("342", ShipInfoDto.EMPTY);
            this.put("343", ShipInfoDto.EMPTY);
            this.put("344", ShipInfoDto.EMPTY);
            this.put("345", ShipInfoDto.EMPTY);
            this.put("346", ShipInfoDto.EMPTY);
            this.put("347", ShipInfoDto.EMPTY);
            this.put("348", ShipInfoDto.EMPTY);
            this.put("349", ShipInfoDto.EMPTY);
            this.put("350", ShipInfoDto.EMPTY);
            this.put("351", ShipInfoDto.EMPTY);
            this.put("352", ShipInfoDto.EMPTY);
            this.put("353", ShipInfoDto.EMPTY);
            this.put("354", ShipInfoDto.EMPTY);
            this.put("355", ShipInfoDto.EMPTY);
            this.put("356", ShipInfoDto.EMPTY);
            this.put("357", ShipInfoDto.EMPTY);
            this.put("358", ShipInfoDto.EMPTY);
            this.put("359", ShipInfoDto.EMPTY);
            this.put("360", ShipInfoDto.EMPTY);
            this.put("361", ShipInfoDto.EMPTY);
            this.put("362", ShipInfoDto.EMPTY);
            this.put("363", ShipInfoDto.EMPTY);
            this.put("364", ShipInfoDto.EMPTY);
            this.put("365", ShipInfoDto.EMPTY);
            this.put("366", ShipInfoDto.EMPTY);
            this.put("367", ShipInfoDto.EMPTY);
            this.put("368", ShipInfoDto.EMPTY);
            this.put("369", ShipInfoDto.EMPTY);
            this.put("370", ShipInfoDto.EMPTY);
            this.put("371", ShipInfoDto.EMPTY);
            this.put("372", ShipInfoDto.EMPTY);
            this.put("373", ShipInfoDto.EMPTY);
            this.put("374", ShipInfoDto.EMPTY);
            this.put("375", ShipInfoDto.EMPTY);
            this.put("376", ShipInfoDto.EMPTY);
            this.put("377", ShipInfoDto.EMPTY);
            this.put("378", ShipInfoDto.EMPTY);
            this.put("379", ShipInfoDto.EMPTY);
            this.put("380", ShipInfoDto.EMPTY);
            this.put("381", ShipInfoDto.EMPTY);
            this.put("382", ShipInfoDto.EMPTY);
            this.put("383", ShipInfoDto.EMPTY);
            this.put("384", ShipInfoDto.EMPTY);
            this.put("385", ShipInfoDto.EMPTY);
            this.put("386", ShipInfoDto.EMPTY);
            this.put("387", ShipInfoDto.EMPTY);
            this.put("388", ShipInfoDto.EMPTY);
            this.put("389", ShipInfoDto.EMPTY);
            this.put("390", ShipInfoDto.EMPTY);
            this.put("391", ShipInfoDto.EMPTY);
            this.put("392", ShipInfoDto.EMPTY);
            this.put("393", ShipInfoDto.EMPTY);
            this.put("394", ShipInfoDto.EMPTY);
            this.put("395", ShipInfoDto.EMPTY);
            this.put("396", ShipInfoDto.EMPTY);
            this.put("397", ShipInfoDto.EMPTY);
            this.put("398", new ShipInfoDto("I-168 Kai", "SS", "I-168", 0, 20, 10));
            this.put("399", new ShipInfoDto("I-58 Kai", "SSV", "I-58", 0, 25, 10));
            this.put("400", new ShipInfoDto("I-8Kai", "SSV", "I-8", 0, 25, 10));
            this.put("401", new ShipInfoDto("I-19 Kai", "SSV", "I-19", 0, 25, 10));
            this.put("402", new ShipInfoDto("Maruyu Kai", "SS", "Maruyu", 0, 10, 10));
            this.put("403", new ShipInfoDto("I-401 Kai", "SSV", "I-401", 0, 30, 25));
            this.put("404", ShipInfoDto.EMPTY);
            this.put("405", ShipInfoDto.EMPTY);
            this.put("406", ShipInfoDto.EMPTY);
            this.put("407", ShipInfoDto.EMPTY);
            this.put("408", ShipInfoDto.EMPTY);
            this.put("409", ShipInfoDto.EMPTY);
            this.put("410", ShipInfoDto.EMPTY);
            this.put("411", ShipInfoDto.EMPTY);
            this.put("412", ShipInfoDto.EMPTY);
            this.put("413", ShipInfoDto.EMPTY);
            this.put("414", ShipInfoDto.EMPTY);
            this.put("415", ShipInfoDto.EMPTY);
            this.put("416", ShipInfoDto.EMPTY);
            this.put("417", ShipInfoDto.EMPTY);
            this.put("418", ShipInfoDto.EMPTY);
            this.put("419", ShipInfoDto.EMPTY);
            this.put("420", ShipInfoDto.EMPTY);
            this.put("421", ShipInfoDto.EMPTY);
            this.put("422", ShipInfoDto.EMPTY);
            this.put("423", ShipInfoDto.EMPTY);
            this.put("424", ShipInfoDto.EMPTY);
            this.put("425", ShipInfoDto.EMPTY);
            this.put("426", ShipInfoDto.EMPTY);
            this.put("427", ShipInfoDto.EMPTY);
            this.put("428", ShipInfoDto.EMPTY);
            this.put("429", ShipInfoDto.EMPTY);
            this.put("430", ShipInfoDto.EMPTY);
            this.put("431", ShipInfoDto.EMPTY);
            this.put("432", ShipInfoDto.EMPTY);
            this.put("433", ShipInfoDto.EMPTY);
            this.put("434", ShipInfoDto.EMPTY);
            this.put("435", ShipInfoDto.EMPTY);
            this.put("436", ShipInfoDto.EMPTY);
            this.put("437", ShipInfoDto.EMPTY);
            this.put("438", ShipInfoDto.EMPTY);
            this.put("439", ShipInfoDto.EMPTY);
            this.put("440", ShipInfoDto.EMPTY);
            this.put("441", ShipInfoDto.EMPTY);
            this.put("442", ShipInfoDto.EMPTY);
            this.put("443", ShipInfoDto.EMPTY);
            this.put("444", ShipInfoDto.EMPTY);
            this.put("445", ShipInfoDto.EMPTY);
            this.put("446", ShipInfoDto.EMPTY);
            this.put("447", ShipInfoDto.EMPTY);
            this.put("448", ShipInfoDto.EMPTY);
            this.put("449", ShipInfoDto.EMPTY);
            this.put("450", ShipInfoDto.EMPTY);
            this.put("451", ShipInfoDto.EMPTY);
            this.put("452", ShipInfoDto.EMPTY);
            this.put("453", ShipInfoDto.EMPTY);
            this.put("454", ShipInfoDto.EMPTY);
            this.put("455", ShipInfoDto.EMPTY);
            this.put("456", ShipInfoDto.EMPTY);
            this.put("457", ShipInfoDto.EMPTY);
            this.put("458", ShipInfoDto.EMPTY);
            this.put("459", ShipInfoDto.EMPTY);
            this.put("460", ShipInfoDto.EMPTY);
            this.put("461", ShipInfoDto.EMPTY);
            this.put("462", ShipInfoDto.EMPTY);
            this.put("463", ShipInfoDto.EMPTY);
            this.put("464", ShipInfoDto.EMPTY);
            this.put("465", ShipInfoDto.EMPTY);
            this.put("466", ShipInfoDto.EMPTY);
            this.put("467", ShipInfoDto.EMPTY);
            this.put("468", ShipInfoDto.EMPTY);
            this.put("469", ShipInfoDto.EMPTY);
            this.put("470", ShipInfoDto.EMPTY);
            this.put("471", ShipInfoDto.EMPTY);
            this.put("472", ShipInfoDto.EMPTY);
            this.put("473", ShipInfoDto.EMPTY);
            this.put("474", ShipInfoDto.EMPTY);
            this.put("475", ShipInfoDto.EMPTY);
            this.put("476", ShipInfoDto.EMPTY);
            this.put("477", ShipInfoDto.EMPTY);
            this.put("478", ShipInfoDto.EMPTY);
            this.put("479", ShipInfoDto.EMPTY);
            this.put("480", ShipInfoDto.EMPTY);
            this.put("481", ShipInfoDto.EMPTY);
            this.put("482", ShipInfoDto.EMPTY);
            this.put("483", ShipInfoDto.EMPTY);
            this.put("484", ShipInfoDto.EMPTY);
            this.put("485", ShipInfoDto.EMPTY);
            this.put("486", ShipInfoDto.EMPTY);
            this.put("487", ShipInfoDto.EMPTY);
            this.put("488", ShipInfoDto.EMPTY);
            this.put("489", ShipInfoDto.EMPTY);
            this.put("490", ShipInfoDto.EMPTY);
            this.put("491", ShipInfoDto.EMPTY);
            this.put("492", ShipInfoDto.EMPTY);
            this.put("493", ShipInfoDto.EMPTY);
            this.put("494", ShipInfoDto.EMPTY);
            this.put("495", ShipInfoDto.EMPTY);
            this.put("496", ShipInfoDto.EMPTY);
            this.put("497", ShipInfoDto.EMPTY);
            this.put("498", ShipInfoDto.EMPTY);
            this.put("499", ShipInfoDto.EMPTY);
            this.put("500", ShipInfoDto.EMPTY);
            this.put("501", new ShipInfoDto("DD I-Class", "DD", "", 0, 0, 0));
            this.put("502", new ShipInfoDto("DD Ro-Class", "DD", "", 0, 0, 0));
            this.put("503", new ShipInfoDto("DD Ha-Class", "DD", "", 0, 0, 0));
            this.put("504", new ShipInfoDto("DD Ni-Class", "DD", "", 0, 0, 0));
            this.put("505", new ShipInfoDto("CL Ho-Class", "CL", "", 0, 0, 0));
            this.put("506", new ShipInfoDto("CL He-Class", "CL", "", 0, 0, 0));
            this.put("507", new ShipInfoDto("CL To-Class", "CL", "", 0, 0, 0));
            this.put("508", new ShipInfoDto("CLT Chi-Class", "CLT", "", 0, 0, 0));
            this.put("509", new ShipInfoDto("CA Ri-Class", "CA", "", 0, 0, 0));
            this.put("510", new ShipInfoDto("CVL Nu-Class", "CVL", "", 0, 0, 0));
            this.put("511", new ShipInfoDto("BB Ru-Class", "BB", "", 0, 0, 0));
            this.put("512", new ShipInfoDto("CV Wo-Class", "CV", "", 0, 0, 0));
            this.put("513", new ShipInfoDto("AP Wa-Class", "AP", "", 0, 0, 0));
            this.put("514", new ShipInfoDto("DD I-Class", "DD", "elite", 0, 0, 0));
            this.put("515", new ShipInfoDto("DD Ro-Class", "DD", "elite", 0, 0, 0));
            this.put("516", new ShipInfoDto("DD Ha-Class", "DD", "elite", 0, 0, 0));
            this.put("517", new ShipInfoDto("DD Ni-Class", "DD", "elite", 0, 0, 0));
            this.put("518", new ShipInfoDto("CL Ho-Class", "CL", "elite", 0, 0, 0));
            this.put("519", new ShipInfoDto("CL He-Class", "CL", "elite", 0, 0, 0));
            this.put("520", new ShipInfoDto("CL To-Class", "CL", "elite", 0, 0, 0));
            this.put("521", new ShipInfoDto("CLT Chi-Class", "CLT", "elite", 0, 0, 0));
            this.put("522", new ShipInfoDto("CA Ri-Class", "CA", "elite", 0, 0, 0));
            this.put("523", new ShipInfoDto("CVL Nu-Class", "CVL", "elite", 0, 0, 0));
            this.put("524", new ShipInfoDto("BB Ru-Class", "BB", "elite", 0, 0, 0));
            this.put("525", new ShipInfoDto("CV Wo-Class", "CV", "elite", 0, 0, 0));
            this.put("526", new ShipInfoDto("AP Wa-Class", "AP", "elite", 0, 0, 0));
            this.put("527", new ShipInfoDto("CA Ri-Class", "CA", "flagship", 0, 0, 0));
            this.put("528", new ShipInfoDto("CV Wo-Class", "CV", "flagship", 0, 0, 0));
            this.put("529", new ShipInfoDto("BB Ru-Class", "BB", "flagship", 0, 0, 0));
            this.put("530", new ShipInfoDto("SS Ka-Class", "SS", "", 0, 0, 0));
            this.put("531", new ShipInfoDto("SS Yo-Class", "SS", "", 0, 0, 0));
            this.put("532", new ShipInfoDto("SS Ka-Class", "SS", "elite", 0, 0, 0));
            this.put("533", new ShipInfoDto("SS Yo-Class", "SS", "elite", 0, 0, 0));
            this.put("534", new ShipInfoDto("SS Ka-Class", "SS", "flagship", 0, 0, 0));
            this.put("535", new ShipInfoDto("SS Yo-Class", "SS", "flagship", 0, 0, 0));
            this.put("536", new ShipInfoDto("Floating Fortress", "BBV", "", 0, 0, 0));
            this.put("537", new ShipInfoDto("Floating Fortress", "BBV", "", 0, 0, 0));
            this.put("538", new ShipInfoDto("Floating Fortress", "BBV", "", 0, 0, 0));
            this.put("539", new ShipInfoDto("Anchorage Oni", "BBV", "", 0, 0, 0));
            this.put("540", new ShipInfoDto("Anchorage Hime", "BBV", "", 0, 0, 0));
            this.put("541", new ShipInfoDto("BB Ta-Class", "BB", "", 0, 0, 0));
            this.put("542", new ShipInfoDto("BB Ta-Class", "BB", "elite", 0, 0, 0));
            this.put("543", new ShipInfoDto("BB Ta-Class", "BB", "flagship", 0, 0, 0));
            this.put("544", new ShipInfoDto("CVB Oni", "BBV", "", 0, 0, 0));
            this.put("545", new ShipInfoDto("CVB Hime", "BBV", "", 0, 0, 0));
            this.put("546", new ShipInfoDto("Southern Ocean Oni", "BBV", "", 0, 0, 0));
            this.put("547", new ShipInfoDto("Southern Ocean War Oni", "BBV", "", 0, 0, 0));
            this.put("548", new ShipInfoDto("Southern Ocean War Hime", "BBV", "", 0, 0, 0));
            this.put("549", new ShipInfoDto("Escort Fortress", "BBV", "", 0, 0, 0));
            this.put("550", new ShipInfoDto("Escort Fortress", "BBV", "", 0, 0, 0));
            this.put("551", new ShipInfoDto("Escort Fortress", "BBV", "", 0, 0, 0));
            this.put("552", new ShipInfoDto("DD Ro-Class", "DD", "flagship", 0, 0, 0));
            this.put("553", new ShipInfoDto("DD Ha-Class", "DD", "flagship", 0, 0, 0));
            this.put("554", new ShipInfoDto("CL Ho-Class", "CL", "flagship", 0, 0, 0));
            this.put("555", new ShipInfoDto("CL He-Class", "CL", "flagship", 0, 0, 0));
            this.put("556", new ShipInfoDto("Airfield Hime", "BBV", "", 0, 0, 0));
            this.put("557", new ShipInfoDto("BB-symbiotic Hime", "BB", "", 0, 0, 0));
            this.put("558", new ShipInfoDto("Wa-Class Transport", "Supply", "flagship", 0, 0, 0));
            this.put("559", new ShipInfoDto("CLT Chi-Class", "CLT", "flagship", 0, 0, 0));
            this.put("560", new ShipInfoDto("CL Nu-Class", "CL", "flagship", 0, 0, 0));
            this.put("561", new ShipInfoDto("BB Re-Class", "BB", "", 0, 0, 0));
            this.put("562", new ShipInfoDto("BB Re-Class", "BB", "elite", 0, 0, 0));
            this.put("563", ShipInfoDto.EMPTY);
            this.put("564", new ShipInfoDto("DD I-Class", "DD", "flagship", 0, 0, 0));
            this.put("565", new ShipInfoDto("CV Wo-Class", "CV", "flagship", 0, 0, 0));
            this.put("566", ShipInfoDto.EMPTY);
            this.put("567", ShipInfoDto.EMPTY);
            this.put("568", ShipInfoDto.EMPTY);
            this.put("569", ShipInfoDto.EMPTY);
            this.put("570", ShipInfoDto.EMPTY);
            this.put("571", ShipInfoDto.EMPTY);
            this.put("572", ShipInfoDto.EMPTY);
            this.put("573", ShipInfoDto.EMPTY);
            this.put("574", ShipInfoDto.EMPTY);
            this.put("575", ShipInfoDto.EMPTY);
            this.put("576", ShipInfoDto.EMPTY);
            this.put("577", ShipInfoDto.EMPTY);
            this.put("578", ShipInfoDto.EMPTY);
            this.put("579", ShipInfoDto.EMPTY);
            this.put("580", ShipInfoDto.EMPTY);
            this.put("581", new ShipInfoDto("NAGARA-Class", "CL", "mist", 0, 0, 0));
            this.put("582", new ShipInfoDto("TAKAO", "CA", "mist", 0, 0, 0));
            this.put("583", new ShipInfoDto("MAYA", "CA", "mist", 0, 0, 0));
            this.put("584", new ShipInfoDto("HARUNA", "BB", "mist", 0, 0, 0));
            this.put("585", new ShipInfoDto("KIRISHIMA", "BB", "mist", 0, 0, 0));
            this.put("586", new ShipInfoDto("KONGOU", "BB", "mist", 0, 0, 0));
            this.put("587", new ShipInfoDto("NAGARA-Class*", "CL", "mist*", 0, 0, 0));
            this.put("588", new ShipInfoDto("TAKAO*", "CA", "mist*", 0, 0, 0));
            this.put("589", new ShipInfoDto("MAYA*", "CA", "mist*", 0, 0, 0));
            this.put("590", new ShipInfoDto("HARUNA*", "BB", "mist*", 0, 0, 0));
            this.put("591", new ShipInfoDto("KIRISHIMA*", "BB", "mist*", 0, 0, 0));
            this.put("592", new ShipInfoDto("KONGOU*", "BB", "mist*", 0, 0, 0));
            this.put("593", ShipInfoDto.EMPTY);
            this.put("594", ShipInfoDto.EMPTY);
            this.put("595", ShipInfoDto.EMPTY);
            this.put("596", ShipInfoDto.EMPTY);
            this.put("597", ShipInfoDto.EMPTY);
            this.put("598", ShipInfoDto.EMPTY);
            this.put("599", ShipInfoDto.EMPTY);
            this.put("600", ShipInfoDto.EMPTY);
        }
    };

    /**
     * 艦娘を取得します
     * 
     * @param id ID
     * @return 艦娘
     */
    public static ShipInfoDto get(String id) {
        return SHIP.get(id);
    }

    /**
     * 艦娘を設定します
     */
    public static void set(String id, ShipInfoDto ship) {
        SHIP.put(id, ship);
    }

    /**
     * IDの一覧を取得します
     * 
     * @return IDの一覧
     */
    public static Set<String> keySet() {
        return SHIP.keySet();
    }
}
